### ISSUE TITLE
add setting to turn off pop up notifications

### ISSUE THREAD

**Issue by BEBEY1** [Yadro/time-tracker#34]
add setting to turn off pop up notifications. Its so annoying when you got another one notification "**You are not tracking time**, there are not task that you track", yes im already know it, thanks, but stop notify my EVERY 5 seconds. Thanks
![image](https://user-images.githubusercontent.com/62993319/184950217-0cc70570-d4b8-4c1f-80bb-5ef6e821b97f.png)

**Comment by Yadro** [comment]
Hi @BEBEY1, I've made it, because you MUST TRACK EVERY single second of working hours in the app! Haha, I'm joking.

**You can disable all notifications in the settings of application.**

(There are only 2 types of notifications: every 15 mins to ping you to log time and every 40 mins, when you already track time, to make sure that current task wasn't changed)
